name: MetaCron Update

on:
  schedule:
    - cron: '0 3 * * *' # Run at 03:00 AM UTC daily
  workflow_dispatch: # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Update API
        run: |
          curl -X POST ${{ secrets.API_URL }}/api/update \
          -H "Authorization: Bearer ${{ secrets.API_KEY }}"
